In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import lxml

In [3]:
url = "https://endoflife.date/windows"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Extract all tables from the page
tables = soup.find_all('table')
print(f"Found {len(tables)} table(s)\n")

# Extract data from each table
all_data = []
for i, table in enumerate(tables):
    rows = table.select('tr, tr.release, tr.release.can-be-hidden')
    table_data = []
    for row in rows:
        cols = row.find_all(['td', 'th'])
        row_data = []
        for col in cols:
            text = col.get_text(separator=' ', strip=True)
            text = ' '.join(text.replace('\n', ' ').replace('\r', ' ').split())
            row_data.append(text)
        if row_data and len(row_data) > 1:
            table_data.append(row_data)
    
    if table_data:
        # Convert to DataFrame for better visualization
        df = pd.DataFrame(table_data[1:], columns=table_data[0])
        all_data.append(df)
        print(f"Table {i+1}:")
        df = pd.concat(all_data, ignore_index=True, sort=False)
       
# Store all dataframes in a dictionary for easy access
tables_dict = {f"table_{i+1}": df for i, df in enumerate(all_data)}


df.head()

Found 2 table(s)

Table 1:
Table 2:

,Release,Released,Active Support,Security Support,Extended Security Updates,Latest,Note,Comment
0,11 26H1 (E),3 months ago (10 Feb 2026),Ends in 2 years and 10 months (13 Mar 2029),Ends in 2 years and 10 months (13 Mar 2029),Unavailable,10.0.28000,NaN,NaN
1,11 26H1 (W),3 months ago (10 Feb 2026),Ends in 1 year and 10 months (14 Mar 2028),Ends in 1 year and 10 months (14 Mar 2028),Unavailable,10.0.28000,NaN,NaN
2,11 25H2 (E),7 months ago (30 Sep 2025),Ends in 2 years and 4 months (10 Oct 2028),Ends in 2 years and 4 months (10 Oct 2028),Unavailable,10.0.26200,NaN,NaN
3,11 25H2 (W),7 months ago (30 Sep 2025),Ends in 1 year and 4 months (12 Oct 2027),Ends in 1 year and 4 months (12 Oct 2027),Unavailable,10.0.26200,NaN,NaN
4,11 24H2 IoT ( LTS ),1 year and 7 months ago (01 Oct 2024),Ends in 3 years (09 Oct 2029),Ends in 8 years (10 Oct 2034),Unavailable,10.0.26100,NaN,NaN

In [95]:
# Combine all extracted tables and save to CSV
if all_data:
    combined_df = pd.concat(all_data, ignore_index=True, sort=False)
    combined_df.to_csv('windows.csv', index=False)
    print('Saved combined table data to windows.csv')
    display(combined_df.head())
else:
    print('No table data found to save.')

Saved combined table data to windows.csv

,Release,Released,Active Support,Security Support,Extended Security Updates,Latest,Note,Comment
0,11 26H1 (E),2 months ago (10 Feb 2026),Ends in 2 years and 11 months (13 Mar 2029),Ends in 2 years and 11 months (13 Mar 2029),Unavailable,10.0.28000,NaN,NaN
1,11 26H1 (W),2 months ago (10 Feb 2026),Ends in 1 year and 11 months (14 Mar 2028),Ends in 1 year and 11 months (14 Mar 2028),Unavailable,10.0.28000,NaN,NaN
2,11 25H2 (E),6 months ago (30 Sep 2025),Ends in 2 years and 6 months (10 Oct 2028),Ends in 2 years and 6 months (10 Oct 2028),Unavailable,10.0.26200,NaN,NaN
3,11 25H2 (W),6 months ago (30 Sep 2025),Ends in 1 year and 6 months (12 Oct 2027),Ends in 1 year and 6 months (12 Oct 2027),Unavailable,10.0.26200,NaN,NaN
4,11 24H2 IoT ( LTS ),1 year and 6 months ago (01 Oct 2024),Ends in 3 years and 6 months (09 Oct 2029),Ends in 8 years (10 Oct 2034),Unavailable,10.0.26100,NaN,NaN